# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  build:
    desc: Build project
    cmds:
      - ./gradlew --stop
      - sudo rm -rf build/
      - ./gradlew build
  test:
    desc: Pass test
    cmds:
      - ./gradlew test
  pre-commit:
    desc: Pass pre-commit
    cmds:
      - sh ./scripts/pre-commit