#!/bin/sh

echo "Running ktlint..."

./gradlew ktlintCheck

if [ $? -ne 0 ]; then
    echo "ktlint failed. Fix formatting issues before committing."
    exit 1
fi

echo "Running Test..."

./gradlew test

if [ $? -ne 0 ]; then
    echo "Test failed"
    exit 1
fi

exit 0